In [1]:
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
sys.path.append('../bin')
from bin.functions import *
from bin.permutation import *
from bin.markov_permutation import *
from bin.entropy import *
from bin.criterions import *
import zlib
%load_ext autoreload
%autoreload 2
np.seterr(all = 'ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [15]:
ts = generate_rw(500)

In [16]:
permutation_entropy(ts, 4, True)

0.9434336860766848

In [17]:
permutation_stationary_entropy(ts, 4, True)

0.9441398075526456

In [ ]:
ts = generate_rw(500)
a = permutation_entropy(ts, 4, True)
b = permutation_stationary_entropy(ts, 4, True)
ts_list = []
diff_list = []
ts_list.append(ts)
diff_list.append(np.abs(a-b))
for i in range(1000):
    if i % 50 == 0:
        print(i)
    ts = generate_rw(500)
    a = permutation_entropy(ts, 4, True)
    b = permutation_stationary_entropy(ts, 4, True)
    ts_list.append(ts)
    diff_list.append(np.abs(a-b))

0
50
100
150
200
250


In [19]:
np.max(diff_list)

0.040057721980971905

In [20]:
diff_list.index(np.max(diff_list))

394

In [22]:
ts = ts_list[394]

In [24]:
transition_matrix = compute_transition_matrix(permutation_series(ts, 4))

matrix_dot = transition_matrix.copy()
for _ in range(6):
    matrix_dot = np.dot(matrix_dot, matrix_dot)

stationary_distribution = np.mean(matrix_dot, axis=0)
stationary_distribution

array([0.0060871 , 0.07908271, 0.09805875, 0.00406129, 0.02639805,
       0.08185322, 0.06344151, 0.        , 0.02978187, 0.        ,
       0.11717132, 0.10793282, 0.00409367, 0.02864627, 0.04820229,
       0.07932205, 0.01824092, 0.00204194, 0.12036254, 0.        ,
       0.07506797, 0.01015373])

In [26]:
np.array(count_permutation(ts, 4))/np.sum(count_permutation(ts, 4))

array([0.00603622, 0.07847082, 0.        , 0.09859155, 0.00402414,
       0.02615694, 0.08249497, 0.06237425, 0.00201207, 0.03018109,
       0.00201207, 0.1167002 , 0.10663984, 0.00402414, 0.02816901,
       0.        , 0.04828974, 0.07847082, 0.01810865, 0.00201207,
       0.11871227, 0.00201207, 0.07444668, 0.01006036])

In [73]:
ts = generate_rw(100)
a = permutation_entropy(ts, 3, False)
b = permutation_stationary_entropy(ts, 3, False)
best = abs(a-b)
best_ts = ts.copy()
for i in range(10000):
    ts = generate_rw(50)
    a = permutation_entropy(ts, 3, False)
    b = permutation_stationary_entropy(ts, 3, False)
    if abs(a-b) > best:
        best = abs(a-b)
        best_ts = ts.copy()

In [74]:
best

1.254100920069825

In [77]:
best_ts50

array([-0.39260646, -2.08437054, -0.40551649, -1.09064641, -0.36809241,
        0.80752944,  0.1558932 ,  1.27890253,  2.53817626,  2.1328892 ,
        3.0072257 ,  3.27157764,  4.45238884,  4.60322452,  3.37288778,
        5.19714955,  5.65101375,  6.34619612,  6.15566209,  7.28370494,
        8.19894225,  8.02760005,  8.32214941,  7.89458465, 10.43305098,
       11.46725021, 11.94720245, 11.51170857, 11.84905965, 11.46064425,
       12.56387034, 11.12820893, 12.78621058, 11.85775525, 11.86883669,
       14.66065246, 14.10875814, 14.66800802, 13.43721032, 13.56402959,
       14.07724916, 15.07325583, 13.54950279, 14.21414521, 14.25219284,
       15.14224272, 15.21598979, 13.00064811, 12.34258098, 12.12070763])

In [92]:
transition_matrix = compute_transition_matrix(permutation_series(best_ts, 3))

matrix_dot = transition_matrix.copy()
for _ in range(6):
    matrix_dot = np.dot(matrix_dot, matrix_dot)

stationary_distribution = np.mean(matrix_dot, axis=0)
stationary_distribution

array([0.81650753, 0.01708237, 0.02066878, 0.03477361, 0.03425938,
       0.07670834])

In [93]:
np.array(count_permutation(best_ts, 3))

array([ 4,  4,  5,  8,  8, 19])

In [91]:
best_ts

array([  0.78883912,  -1.03557922,  -2.28052842,  -1.32891174,
        -2.36054127,  -3.56507259,  -4.07144419,  -3.07387429,
        -3.28704729,  -4.48855711,  -2.14635158,  -3.31386817,
        -3.83172644,  -3.3812219 ,  -4.7974961 ,  -4.16158266,
        -5.21668725,  -5.4503632 ,  -6.74176088,  -8.5721975 ,
        -8.74613783,  -8.3330683 ,  -9.11204094,  -8.65026479,
        -9.48117187,  -9.87012853,  -9.54147149,  -9.74335678,
        -9.78846744, -10.77506745, -10.62531122, -11.00490012,
       -10.96102729, -12.31739884, -13.44736491, -13.61838052,
       -14.23910743, -14.40690928, -15.03723157, -15.42083361,
       -14.96475862, -15.52425256, -15.94065252, -13.52669897,
       -14.86865021, -14.74123443, -13.34553767, -13.28026844,
       -11.73404145, -10.8785416 ])

In [94]:
matrix_dot

array([[1.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.77498986, 0.02094748, 0.02534538, 0.04264161, 0.04201103,
        0.09406465],
       [0.77107443, 0.02131199, 0.02578641, 0.04338362, 0.04274207,
        0.09570147],
       [0.77855819, 0.02061529, 0.02494343, 0.04196537, 0.04134479,
        0.09257292],
       [0.80115157, 0.01851194, 0.02239849, 0.03768371, 0.03712645,
        0.08312784],
       [0.77327112, 0.02110749, 0.02553897, 0.04296733, 0.04233193,
        0.09478316]])

In [ ]:
# Создание фигуры и осей
fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# Временной ряд
axs[0].plot(best_ts50)
axs[0].set_title('Временной ряд')

# Первая гистограмма
axs[1].hist(hist_data1, bins=30, color='blue', alpha=0.7)
axs[1].set_title('Гистограмма 1')

# Вторая гистограмма
axs[2].hist(hist_data2, bins=30, color='green', alpha=0.7)
axs[2].set_title('Гистограмма 2')

# Настройка расстояний между графиками
plt.tight_layout()

# Показ графика
plt.show()
