In [49]:
import sys
sys.path.append('../bin')
from bin.functions import *
# import pandas as pd
# import numpy as np
# import sklearn as sk
# import statsmodels.api as sm
import matplotlib.pyplot as plt
# import datetime as dt
# from statsmodels.iolib.table import SimpleTable
# from sklearn.metrics import r2_score
# import matplotlib
# import random as rd
# from sklearn import metrics
# from sklearn.metrics import mean_squared_error, mean_absolute_percentage_error
# import math
# import itertools as it
# import seaborn as sn
# import scipy as sp
#
# import plotly
# import plotly.graph_objs as go
# import plotly.express as px
# from plotly.subplots import make_subplots
np.seterr(divide = 'ignore')

{'divide': 'ignore', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [2]:
not_simmetry3 = []
not_simmetry4 = []

In [3]:
for i in range(100):
    if i%20 == 0:
        print(i)
    rw = random_walk(date_end="30/12/2023 00:00:00")
    ts_perm3 = count_permutation(rw, 3)
    ts_perm4 = count_permutation(rw, 4)
    cr3 = multiply_equals_test(ts_perm3)
    if sum(cr3[0]) != 0:
        print(cr3)
        not_simmetry3.append([rw,ts_perm3])
    cr4 = multiply_equals_test(ts_perm4)
    if sum(cr4[0]) != 0:
        print(cr4)
        not_simmetry4.append([rw,ts_perm4])

0


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.02800121, 0.92191375, 0.92191375]), 0.016952427508441503, 0.016666666666666666)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.04046517, 0.82977486, 0.82977486]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False]), array([0.00952535, 0.66724453, 0.66724453]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([0.00480949, 0.99958163, 0.99958163, 0.99958163, 1.        ,
       0.98765599, 0.99958163, 0.99618693, 1.        , 0.53394536,
       0.99958163, 0.99958163]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([0.02477334, 0.96294422, 0.99051233, 0.99923605, 0.99923605,
       0.99051233, 0.99923605, 0.99923605, 0.96117311, 0.99051233,
       0.72439412, 0.99923605]), 0.004265318777560645, 0.004166666666666667)
20


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([7.59340656e-06, 8.27394453e-01, 8.27394453e-01]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([5.44431312e-05, 9.95338336e-01, 9.42813240e-01, 9.95338336e-01,
       9.95338336e-01, 9.95338336e-01, 9.86175096e-01, 9.86344502e-01,
       9.95338336e-01, 2.62405753e-01, 6.72506541e-01, 5.60202660e-01]), 0.004265318777560645, 0.004166666666666667)
(array([ True, False, False]), array([0.00402805, 0.98926341, 0.98926341]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False]), array([8.01953424e-06, 2.68914496e-01, 2.68914496e-01]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([1.76799649e-05, 4.39870055e-01, 2.46434927e-01, 9.84519272e-01,
       7.36440930e-01, 9.84519272e-01, 8.90394997e-01, 8.34542343e-01,
       9.8484

C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.02670446, 0.7630692 , 0.7630692 ]), 0.016952427508441503, 0.016666666666666666)
(array([False, False, False, False, False,  True, False, False, False,
       False, False, False]), array([0.60283024, 0.95684333, 0.95827922, 0.95827922, 0.99645416,
       0.00900383, 0.95684333, 0.2521784 , 0.99645416, 0.83835301,
       0.95827922, 0.95684333]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


40


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([2.30386914e-05, 7.93662394e-01, 7.93662394e-01]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([1.54388918e-04, 8.55448063e-01, 4.48360920e-01, 9.68884331e-01,
       9.23210731e-01, 9.23210731e-01, 9.23210731e-01, 9.23210731e-01,
       9.68884331e-01, 9.23210731e-01, 8.55448063e-01, 9.23210731e-01]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.00211917, 0.70743856, 0.70743856]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([0.00409262, 0.92227306, 0.89652474, 0.99708366, 0.89652474,
       0.997523  , 0.49247309, 0.93908977, 0.997523  , 0.997523  ,
       0.997523  , 0.89652474]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.00950782, 0.92343274, 0.92343274]), 0.016952427508441503, 0.016666666666666666)
60


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.00165545, 0.7695038 , 0.7695038 ]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([0.00378607, 0.98216722, 0.69410805, 0.98216722, 0.36189983,
       0.58633143, 0.98216722, 0.58633143, 0.58633143, 0.98216722,
       0.58633143, 0.98216722]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([False, False, False, False, False, False, False,  True, False,
       False, False, False]), array([0.98971383, 0.98971383, 0.90171437, 0.8718179 , 0.98971383,
       0.94162506, 0.98971383, 0.00998184, 0.98971383, 0.99715023,
       1.        , 0.98971383]), 0.004265318777560645, 0.004166666666666667)
(array([ True, False, False]), array([0.01698042, 0.5996518 , 0.5996518 ]), 0.016952427508441503, 0.016666666666666666)
(array([False, False, False, False, False, False, False, False, False,
        True, False, False]), array([0.92057769, 0.18101712, 0.92057769, 0.99569714, 0.54569962,
       0.99569714, 0.96155571, 0.77999386, 0.92057769, 0.03085395,
       0.99569714, 0.98589972]), 0.004265318777560645, 0.004166666666666667)
(array([ True, False, False]), array([0.02300208, 0.9245539 , 0.9245539 ]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False]), array([0.00983765, 0.12057441, 0.12057441]), 0.016952427508441503, 0.016666666666666666)
(array([ True, F

C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


80


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.02358937, 0.9373458 , 0.9373458 ]), 0.016952427508441503, 0.016666666666666666)
(array([False, False, False, False, False, False, False,  True, False,
       False, False, False]), array([0.14235765, 0.96578964, 0.99993172, 0.99993172, 0.99993172,
       0.99993172, 0.9731655 , 0.0402465 , 0.99993172, 0.99993172,
       0.99721623, 0.99993172]), 0.004265318777560645, 0.004166666666666667)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.03767744, 0.4690707 , 0.4690707 ]), 0.016952427508441503, 0.016666666666666666)


C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))
C:\Users\vitya\AppData\Roaming\Python\Python310\site-packages\statsmodels\stats\multitest.py:186: RuntimeWarning: divide by zero encountered in log1p
  np.log1p(-pvals))


(array([ True, False, False]), array([0.00292453, 0.50591575, 0.50591575]), 0.016952427508441503, 0.016666666666666666)
(array([ True, False, False, False, False, False, False, False, False,
       False, False, False]), array([3.15840293e-05, 9.99998483e-01, 9.63842750e-01, 9.99998483e-01,
       9.99998483e-01, 9.99998483e-01, 9.99998483e-01, 8.95371375e-01,
       9.99949779e-01, 9.95627961e-01, 9.08362572e-01, 9.93167334e-01]), 0.004265318777560645, 0.004166666666666667)


In [4]:
len(not_simmetry3)/100

0.18

In [5]:
len(not_simmetry4)/100

0.13

In [9]:
simmetry3 = []
simmetry4 = []

In [11]:
for i in range(100):
    if i%20 == 0:
        print(i)
    ts = generate_ts(date_end="30/12/2023 00:00:00")
    ts_perm3 = count_permutation(ts, 3)
    ts_perm4 = count_permutation(ts, 4)
    cr3 = multiply_equals_test(ts_perm3)
    if sum(cr3[0]) == 0:
        print(cr3)
        simmetry3.append([ts,ts_perm3])
    cr4 = multiply_equals_test(ts_perm4)
    if sum(cr4[0]) == 0:
        print(cr4)
        simmetry4.append([ts,ts_perm4])

0
20
40
60
80


In [12]:
len(simmetry3)/100

0.14

In [13]:
len(simmetry4)/100

0.14

In [32]:
not_simmetry3_hs = []
not_simmetry3_hb = []
not_simmetry3_sh = []
not_simmetry3_hommel = []

In [33]:
simmetry3_hs = []
simmetry3_hb = []
simmetry3_sh = []
simmetry3_hommel = []

In [34]:
for i in range(100):
    if i%10 == 0:
        print(i)
    ts = generate_ts(date_end="30/10/2023 00:00:00")
    ts_perm3 = count_permutation(ts, 3)
    cr = multiply_equals_test(ts_perm3)
    if sum(cr[0]) == 0:
        simmetry3_hs.append([ts,ts_perm3])
    cr_hb = multiply_equals_test(ts_perm3, method="holm")
    if sum(cr_hb[0]) == 0:
        simmetry3_hb.append([ts,ts_perm3])
    cr_sh = multiply_equals_test(ts_perm3, method="simes-hochberg")
    if sum(cr_sh[0]) == 0:
        simmetry3_sh.append([ts,ts_perm3])
    cr_hommel = multiply_equals_test(ts_perm3, method="hommel")
    if sum(cr_hommel[0]) == 0:
        simmetry3_hommel.append([ts,ts_perm3])
    rw = random_walk(date_end="30/10/2023 00:00:00")
    ts_perm3 = count_permutation(rw, 3)
    cr = multiply_equals_test(ts_perm3)
    if sum(cr[0]) != 0:
        not_simmetry3_hs.append([ts,ts_perm3])
    cr_hb = multiply_equals_test(ts_perm3, method="holm")
    if sum(cr_hb[0]) != 0:
        not_simmetry3_hb.append([ts,ts_perm3])
    cr_sh = multiply_equals_test(ts_perm3, method="simes-hochberg")
    if sum(cr_sh[0]) != 0:
        not_simmetry3_sh.append([ts,ts_perm3])
    cr_hommel = multiply_equals_test(ts_perm3, method="hommel")
    if sum(cr_hommel[0]) != 0:
        not_simmetry3_hommel.append([ts,ts_perm3])

0
10
20
30
40
50
60
70
80
90


In [40]:
print(f"Holm-Sidak: FNR: {len(not_simmetry3_hs)/100}; FPR: {len(simmetry3_hs)/100}")
print(f"Holm-Benferonni: FNR: {len(not_simmetry3_hb)/100}; FPR: {len(simmetry3_hb)/100}")
print(f"Simes-Hochberg: FNR: {len(not_simmetry3_sh)/100}; FPR: {len(simmetry3_sh)/100}")
print(f"Hommel: FNR: {len(not_simmetry3_hommel)/100}; FPR: {len(simmetry3_hommel)/100}")

Holm-Sidak: FNR: 0.09; FPR: 0.0
Holm-Benferonni: FNR: 0.08; FPR: 0.0
Simes-Hochberg: FNR: 0.08; FPR: 0.0
Hommel: FNR: 0.08; FPR: 0.0


In [36]:
not_simmetry4_hs = []
not_simmetry4_hb = []
not_simmetry4_sh = []
not_simmetry4_hommel = []

In [37]:
simmetry4_hs = []
simmetry4_hb = []
simmetry4_sh = []
simmetry4_hommel = []

In [38]:
for i in range(100):
    if i%10 == 0:
        print(i)
    ts = generate_ts(date_end="30/10/2023 00:00:00")
    ts_perm4 = count_permutation(ts, 4)
    cr = multiply_equals_test(ts_perm4)
    if sum(cr[0]) == 0:
        simmetry4_hs.append([ts,ts_perm4])
    cr_hb = multiply_equals_test(ts_perm4, method="holm")
    if sum(cr_hb[0]) == 0:
        simmetry4_hb.append([ts,ts_perm4])
    cr_sh = multiply_equals_test(ts_perm4, method="simes-hochberg")
    if sum(cr_sh[0]) == 0:
        simmetry4_sh.append([ts,ts_perm4])
    cr_hommel = multiply_equals_test(ts_perm4, method="hommel")
    if sum(cr_hommel[0]) == 0:
        simmetry4_hommel.append([ts,ts_perm4])
    rw = random_walk(date_end="30/10/2023 00:00:00")
    ts_perm4 = count_permutation(rw, 4)
    cr = multiply_equals_test(ts_perm4)
    if sum(cr[0]) != 0:
        not_simmetry4_hs.append([ts,ts_perm4])
    cr_hb = multiply_equals_test(ts_perm4, method="holm")
    if sum(cr_hb[0]) != 0:
        not_simmetry4_hb.append([ts,ts_perm4])
    cr_sh = multiply_equals_test(ts_perm4, method="simes-hochberg")
    if sum(cr_sh[0]) != 0:
        not_simmetry4_sh.append([ts,ts_perm4])
    cr_hommel = multiply_equals_test(ts_perm4, method="hommel")
    if sum(cr_hommel[0]) != 0:
        not_simmetry4_hommel.append([ts,ts_perm4])

0
10
20
30
40
50
60
70
80
90


In [42]:
print(f"Holm-Sidak: FNR: {len(not_simmetry4_hs)/100}; FPR: {len(simmetry4_hs)/100}")
print(f"Holm-Benferonni: FNR: {len(not_simmetry4_hb)/100}; FPR: {len(simmetry4_hb)/100}")
print(f"Simes-Hochberg: FNR: {len(not_simmetry4_sh)/100}; FPR: {len(simmetry4_sh)/100}")
print(f"Hommel: FNR: {len(not_simmetry4_hommel)/100}; FPR: {len(simmetry4_hommel)/100}")

Holm-Sidak: FNR: 0.12; FPR: 0.0
Holm-Benferonni: FNR: 0.12; FPR: 0.0
Simes-Hochberg: FNR: 0.12; FPR: 0.0
Hommel: FNR: 0.12; FPR: 0.0


In [45]:
result_hs = []
result_hb = []
result_sh = []
result_hommel = []

In [54]:
for alpha in [0.01*k for k in range(9, 100, 5)]:
        fp = {"holm-sidak":0,'holm':0,"simes-hochberg":0,"hommel":0}
        fn = {"holm-sidak":0,'holm':0,"simes-hochberg":0,"hommel":0}
        for i in range(100):
            if i%50 == 0:
                print(i, alpha)
            ts = generate_ts(date_end="30/09/2023 00:00:00")
            ts_perm3 = count_permutation(ts, 3)
            for method in ["holm-sidak", 'holm',"simes-hochberg","hommel"]:
                cr = multiply_equals_test(ts_perm3, alpha=alpha, method=method)
                if sum(cr[0]) == 0:
                    fp[method]+=1

            rw = random_walk(date_end="30/09/2023 00:00:00")
            ts_perm3 = count_permutation(rw, 3)
            for method in ["holm-sidak", 'holm',"simes-hochberg","hommel"]:
                cr = multiply_equals_test(ts_perm3, alpha=alpha, method=method)
                if sum(cr[0]) != 0:
                    fn[method]+=1
        result_hs.append([alpha, fp["holm-sidak"], fn["holm-sidak"]])
        result_hb.append([alpha, fp["holm"], fn["holm"]])
        result_sh.append([alpha, fp["simes-hochberg"], fn["simes-hochberg"]])
        result_hommel.append([alpha, fp["hommel"], fn["hommel"]])


0 0.09
50 0.09
0 0.14
50 0.14
0 0.19
50 0.19
0 0.24
50 0.24
0 0.29
50 0.29
0 0.34


KeyboardInterrupt: 

In [59]:
result_hommel

[[0.01, 0, 7],
 [0.02, 0, 11],
 [0.03, 0, 6],
 [0.04, 0, 16],
 [0.05, 0, 14],
 [0.06, 0, 16],
 [0.07, 0, 18],
 [0.08, 0, 19],
 [0.09, 0, 23],
 [0.14, 0, 27],
 [0.19, 0, 31],
 [0.24, 0, 33],
 [0.29, 0, 30]]

In [60]:
result_sh

[[0.01, 0, 7],
 [0.02, 0, 11],
 [0.03, 0, 6],
 [0.04, 0, 16],
 [0.05, 0, 14],
 [0.06, 0, 16],
 [0.07, 0, 18],
 [0.08, 0, 18],
 [0.09, 0, 23],
 [0.14, 0, 24],
 [0.19, 0, 31],
 [0.24, 0, 33],
 [0.29, 0, 30]]

In [61]:
result_hs

[[0.01, 0, 7],
 [0.02, 0, 11],
 [0.03, 0, 6],
 [0.04, 0, 16],
 [0.05, 0, 15],
 [0.06, 0, 16],
 [0.07, 0, 17],
 [0.08, 0, 18],
 [0.09, 0, 22],
 [0.14, 0, 21],
 [0.19, 0, 31],
 [0.24, 0, 32],
 [0.29, 0, 25]]

In [62]:
result_hb

[[0.01, 0, 7],
 [0.02, 0, 11],
 [0.03, 0, 6],
 [0.04, 0, 16],
 [0.05, 0, 14],
 [0.06, 0, 16],
 [0.07, 0, 16],
 [0.08, 0, 17],
 [0.09, 0, 22],
 [0.14, 0, 21],
 [0.19, 0, 29],
 [0.24, 0, 30],
 [0.29, 0, 22]]

In [67]:
sim4_hb = []
not_sim4_hb = []
for i in range(300):
    if i%50 == 0:
        print(i)
    ts = generate_ts(date_end="30/10/2023 00:00:00")
    ts_perm4 = count_permutation(ts, 4)
    cr_hb = multiply_equals_test(ts_perm4, method="holm", alpha=0.03)
    if sum(cr_hb[0]) == 0:
        sim4_hb.append([ts,ts_perm4])
    rw = random_walk(date_end="30/10/2023 00:00:00")
    ts_perm4 = count_permutation(rw, 4)
    cr_hb = multiply_equals_test(ts_perm4, method="holm", alpha=0.03)
    if sum(cr_hb[0]) != 0:
        not_sim4_hb.append([ts,ts_perm4])

0
50
100
150
200
250


In [68]:
print(f"Holm-Bonferoni: FNR: {len(not_sim4_hb)/300}; FPR: {len(sim4_hb)/300}")

Holm-Bonferoni: FNR: 0.07666666666666666; FPR: 0.0


In [69]:
dates = ["30/07/2023 00:00:00", "30/08/2023 00:00:00", "30/09/2023 00:00:00", "30/10/2023 00:00:00", "30/11/2023 00:00:00", "30/12/2023 00:00:00", "30/01/2024 00:00:00", "30/06/2024 00:00:00", "30/06/2025 00:00:00"]
result_hs_date = []
result_hb_date = []
result_sh_date = []
result_hommel_date = []

In [70]:
for date in dates:
        fp = {"holm-sidak":0,'holm':0,"simes-hochberg":0,"hommel":0}
        fn = {"holm-sidak":0,'holm':0,"simes-hochberg":0,"hommel":0}
        for i in range(100):
            if i%50 == 0:
                print(i, date)
            ts = generate_ts(date_end=date)
            ts_perm3 = count_permutation(ts, 3)
            for method in ["holm-sidak", 'holm',"simes-hochberg","hommel"]:
                cr = multiply_equals_test(ts_perm3, alpha=0.03, method=method)
                if sum(cr[0]) == 0:
                    fp[method]+=1

            rw = random_walk(date_end=date)
            ts_perm3 = count_permutation(rw, 3)
            for method in ["holm-sidak", 'holm',"simes-hochberg","hommel"]:
                cr = multiply_equals_test(ts_perm3, alpha=0.03, method=method)
                if sum(cr[0]) != 0:
                    fn[method]+=1
        result_hs_date.append([date, fp["holm-sidak"], fn["holm-sidak"]])
        result_hb_date.append([date, fp["holm"], fn["holm"]])
        result_sh_date.append([date, fp["simes-hochberg"], fn["simes-hochberg"]])
        result_hommel_date.append([date, fp["hommel"], fn["hommel"]])

0 30/07/2023 00:00:00
50 30/07/2023 00:00:00
0 30/08/2023 00:00:00
50 30/08/2023 00:00:00
0 30/09/2023 00:00:00
50 30/09/2023 00:00:00
0 30/10/2023 00:00:00
50 30/10/2023 00:00:00
0 30/11/2023 00:00:00
50 30/11/2023 00:00:00
0 30/12/2023 00:00:00
50 30/12/2023 00:00:00
0 30/01/2024 00:00:00
50 30/01/2024 00:00:00
0 30/02/2024 00:00:00


ValueError: could not convert string to Timestamp

In [71]:
result_hs_date

[['30/07/2023 00:00:00', 0, 12],
 ['30/08/2023 00:00:00', 0, 15],
 ['30/09/2023 00:00:00', 0, 17],
 ['30/10/2023 00:00:00', 0, 15],
 ['30/11/2023 00:00:00', 0, 11],
 ['30/12/2023 00:00:00', 0, 12],
 ['30/01/2024 00:00:00', 0, 9]]

In [72]:
result_hb_date

[['30/07/2023 00:00:00', 0, 12],
 ['30/08/2023 00:00:00', 0, 15],
 ['30/09/2023 00:00:00', 0, 17],
 ['30/10/2023 00:00:00', 0, 15],
 ['30/11/2023 00:00:00', 0, 11],
 ['30/12/2023 00:00:00', 0, 12],
 ['30/01/2024 00:00:00', 0, 9]]

In [73]:
result_sh_date

[['30/07/2023 00:00:00', 0, 12],
 ['30/08/2023 00:00:00', 0, 15],
 ['30/09/2023 00:00:00', 0, 17],
 ['30/10/2023 00:00:00', 0, 15],
 ['30/11/2023 00:00:00', 0, 12],
 ['30/12/2023 00:00:00', 0, 13],
 ['30/01/2024 00:00:00', 0, 9]]

In [74]:
result_hommel_date

[['30/07/2023 00:00:00', 0, 12],
 ['30/08/2023 00:00:00', 0, 15],
 ['30/09/2023 00:00:00', 0, 18],
 ['30/10/2023 00:00:00', 0, 15],
 ['30/11/2023 00:00:00', 0, 12],
 ['30/12/2023 00:00:00', 0, 13],
 ['30/01/2024 00:00:00', 0, 9]]